name: Push to Replicate

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  push-to-replicate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Install Cog directly
        run: |
          sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)
          sudo chmod +x /usr/local/bin/cog
          cog --version

      - name: Configure Docker for Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          mkdir -p ~/.config/
          echo '{"token":"'$REPLICATE_API_TOKEN'"}' > ~/.config/replicate
          echo $REPLICATE_API_TOKEN | docker login --username=token --password-stdin r8.im

      - name: Push to Replicate
        run: |
          cog push r8.im/anon4207/multipony
