name: Push to Replicate

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  push-to-replicate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true

      # Install cog directly
      - name: Install Cog
        run: |
          sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)
          sudo chmod +x /usr/local/bin/cog
          cog --version

      # Authenticate with Replicate using token
      - name: Configure Replicate credentials
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          mkdir -p ~/.config
          echo "{\"token\":\"$REPLICATE_API_TOKEN\"}" > ~/.config/replicate

      # Push to Replicate with build args to skip CUDA check
      - name: Push to Replicate
        run: |
          COG_SKIP_CUDA_CHECK=1 cog push r8.im/anon4207/multipony
