name: Push to Replicate

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  push-to-replicate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Set up Cog
        uses: replicate/setup-cog@v1
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}
      
      - name: Push to Replicate
        run: |
          cog push r8.im/your-username/cyberrealistic-pony-v8
